export const GET_CARDS = "GET_CARDS";
export const SWITCH_CARD_FAVORITE = "SWITCH_CARD_FAVORITE";
export const SEARCH_CARD = "SEARCH_CARD";
export const SET_IS_LOADING_PROGRESS = "SET_IS_LOADING_PROGRESS";
export const SET_DETAILED_CARD = "SET_DETAILED_CARD";
export const GET_CARDS_BY_FILTER = "GET_CARDS_BY_FILTER";